version: '2'

services:

    nginx:
        restart: always
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/default.conf
            - static_volume:/app/backend/static
    server:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/server.dockerfile
        volumes:
            - static_volume:/app/backend/static
        expose:
            - 8000
        env_file:
            - .env

    celery-worker:
        build:
            context: .
            dockerfile: ./docker/worker.dockerfile
        command: celery -A celery_app worker --loglevel=info
        volumes:
            - .:/app
        depends_on:
            - redis

    celery-flower:
        image: mher/flower:0.9.7
        ports:
            - "5555:5555"
        command: flower --broker=redis://redis:6379 --port=5555
        depends_on:
            - celery-worker

    redis:
        restart: unless-stopped
        image: redis:7.0.5-alpine 
        expose:
            - 6379
    
volumes:
    static_volume: {}
    postgres_data: {}
