version: '2'

services:

    nginx:
        restart: always
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - static_volume:/app/backend/static
        depends_on:
            - server

    server:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/server.dockerfile
        volumes:
            - static_volume:/app/backend/static
        ports:
            - "8000:8000"
        env_file:
            - .env

    celery-worker:
        build:
            context: .
            dockerfile: ./docker/worker.dockerfile
        command: celery -A celery_app.celery_app worker --loglevel=info
        volumes:
            - .:/app
        depends_on:
            - redis

    redis:
        restart: unless-stopped
        image: redis:7.0.5-alpine 
        expose:
            - 6379
    
volumes:
    static_volume: {}
    postgres_data: {}
